### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by UnEnanoMas** [DataLiontje/SlapperModel#1]
I ask, isn't it easier, import the skin to Minecraft BE, and put it on, and then you use the / slapper spawn human name and you already have it?

Maybe it's okay for ... I don't think of anything xd

**Comment by DataLiontje** [comment]
Its really hard to do that on mobile devices.
And Minecraft keeps patching that feature where you can get your own 3D skins.
So no in my opinion this is way easier.
